excelのタイムスタンプが更新される場合、データの再読み込みができないバグを修正
nablarch/nablarch-testing pull request #37
Opened 2021-04-22 00:21 UTC by koyi2016

2021-04-26 08:18 UTC, kumagoro1202 requested changes

2021-04-26 08:18 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/reader/TestDataParsingTemplate.java
> +     * @param saveCacheFlag  読み込んだファイルのデータをキャッシュに保存するか
"Flag"をつける必然性がないので削除してください。

2021-04-26 08:18 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +    public void test7() throws Exception {
やはりtest7として分ける意味がありません。
test6と統合してください。

> Excelの応答電文の数を上回るリクエストがやってきた場合のテスト。（noの2で落ちたことが分かる）

というtest6のJavaDocを編集して

> Excelに記載された応答電文の数を上回るリクエストが来た場合のテスト。
> ・応答電文の数を上回りエラーとなった場合、何回目のリクエストでエラーとなったかがわかること
> ・Excelを更新してタイムスタンプが変わった場合は1つ目のリクエストから再読み込みされエラーとならないこと
> ・再読み込みした場合、Excelの変更内容が応答電文に反映されること

とテスト内容がわかるようにしてください。

2021-05-10 00:14 UTC, kumagoro1202 requested changes

2021-05-10 00:14 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +        // ファイルのタイムスタンプを書き換える
ここでやりたいのはファイルのタイムスタンプを書き換えることではなく、元のデータに戻すことですよね？

2021-05-10 00:14 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +        File fileBack = filePathSetting.getFileIfExists(SendSyncSupport.SEND_SYNC_TEST_DATA_BASE_PATH, "RM11AD0108_copy");
ファイルをコピーする似たような処理が何度も出てきてテストの見通しが悪いのでメソッドに切り出してください。

2021-05-10 00:14 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +        sendSync = MessageSender.sendSync(new SyncMessage("RM11AD0108")
どういう意図でここでもう一度メッセージ送信していますか？

2021-05-10 06:47 UTC, koyi2016 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +        // ファイルのタイムスタンプを書き換える
行197以下のソースコードを廃止したため、上記のコメントを削除しました。

2021-05-10 06:48 UTC, koyi2016 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +        File fileBack = filePathSetting.getFileIfExists(SendSyncSupport.SEND_SYNC_TEST_DATA_BASE_PATH, "RM11AD0108_copy");
ご指摘通り、ファイルコピーの処理を新しいメソッドとして切り出しました。

2021-05-10 06:49 UTC, koyi2016 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +        sendSync = MessageSender.sendSync(new SyncMessage("RM11AD0108")
3回目のメッセージ送信に関するソースコードを削除しました。

2021-05-10 06:50 UTC, koyi2016 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +    public void test7() throws Exception {
ご指摘通り、テストケースを統合しました。
test6のjavadocを更新しました。

2021-05-10 06:53 UTC, koyi2016 commented on src/main/java/nablarch/test/core/reader/TestDataParsingTemplate.java
> +     * @param saveCacheFlag  読み込んだファイルのデータをキャッシュに保存するか
Flagを削除しました。

2021-05-10 07:20 UTC, kumagoro1202 requested changes

2021-05-10 07:20 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +    public void fileCopy(FilePathSetting filePathSetting, File file , String fileName) throws Exception {
filePathSettingやfileNameという引数は何のために使われるのかわかりにくいです。
シンプルに以下のような感じでどうでしょう。
```java
    private void copyFile(File inFile, File outFile) throws IOException {
        FileChannel in = new FileInputStream(inFile).getChannel();;
        FileChannel out = new FileOutputStream(outFile).getChannel();;
        in.transferTo(0, in.size(), out);
    }
```

呼び出し元
```java
copyFile(getFile(filePathSetting, "RM11AD0108_copy"), file);
```

2021-05-10 07:20 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +        if(file.exists()) {
ここがfalseになるとExcelのコピーがされません。
file.delete()された後にコピーでエラーになった場合ファイルが無いという状態になる可能性があります。

2021-05-10 07:20 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +            fileCopy(filePathSetting, file, "RM11AD0108_copy");
RM11AD0108_copyはわかりにくいのでoriginalというような名前にしましょうという指摘が反映されていないです。

2021-05-10 08:22 UTC, koyi2016 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +    public void fileCopy(FilePathSetting filePathSetting, File file , String fileName) throws Exception {
ご指摘通り、引き出すメソッドをシンプルに修正しました。

2021-05-10 08:23 UTC, koyi2016 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +        if(file.exists()) {
常にコピー処理を行っているため、if文を削除しました。

2021-05-10 08:23 UTC, koyi2016 commented on src/test/java/nablarch/test/core/messaging/MockMessagingContextTest.java
> +            fileCopy(filePathSetting, file, "RM11AD0108_copy");
修正漏れです。
ファイル名をRM11AD0108_copyからRM11AD0108_originalに修正しました。

2021-05-12 03:00 UTC, kumagoro1202 approved these changes

2021-05-12 03:00 UTC, merged