NTFのHTTPのテストでHTTPメソッドおよびクエリパラメータを指定できるようにしました
nablarch/nablarch-testing pull request #56
Opened 2023-05-25 09:41 UTC by chupaaaaaaan

2023-05-25 10:57 UTC, kumagoro1202 requested changes

2023-05-25 10:57 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +        List<Map<String, String>> rawQueryParams;
これはif文内のスコープでしか参照されないのでif文内で宣言してください。

2023-05-25 10:57 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +            }
このタイミングでURLエンコードするのは違和感があります。HttpRequestTestSupport#appendQueryParamsToUriでURIに付加する際にエンコードするべきです。

2023-05-25 10:57 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    }
POST指定している時にクエリーパラメータにnull指定しないといけないのは不便なので、引数がHTTPメソッドありでクエリーパラメータなしのcreateHttpRequestWithConversionもあったほうがいいと思います。

2023-05-25 10:57 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/TestCaseInfo.java
> +            List<Map<String, String>> queryParams) {
引数にcookieを持ちqueryPramsを持たないpublicなメソッドがなくなってしまっていて後方互換性がなくなっています。

2023-05-25 10:57 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +     * @return
Javadocを中途半端な状態にしないでください。書くならちゃんと書く、書かないなら書かないで自動生成された@returnをそのままにするようなことはしないでください。

2023-05-25 10:57 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                // Cookieをリクエストスコープに移送
このコメントは何のことですか？

2023-05-25 10:57 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                    // それ以外は、Excelに設定したCookieが設定されているはず
Cookieというのはコメントをコピペして修正漏れ？

2023-05-25 10:57 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                    }
Excelの期待値にURLエンコードされたものを記載していますが、わかりにくいのでassertする時にURLエンコードしたほうがいいと思います。URLエンコードされた期待値が正しいのか見てわからないので。

2023-05-25 10:57 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +        });
Cookieというところは修正漏れ？

2023-05-25 10:57 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                // Cookieをリクエストスコープに移送
このコメントはどういう意味？

2023-05-26 01:22 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +        List<Map<String, String>> rawQueryParams;
修正しました。

2023-05-26 01:26 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    }
メソッド追加しました。

2023-05-26 01:38 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +            }
HttpRequestTestSupport#appendQueryParamsToUri で処理するように修正しました。

2023-05-26 01:46 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/TestCaseInfo.java
> +            List<Map<String, String>> queryParams) {
コンストラクタを追加しました。

2023-05-26 01:49 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +     * @return
すみません、対応漏れていました。記載追加しました。

2023-05-26 01:51 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                // Cookieをリクエストスコープに移送
別のテストから持ってきた部分の修正が漏れていました。記載を削除しました。

2023-05-26 01:51 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                    // それ以外は、Excelに設定したCookieが設定されているはず
修正漏れだったので、「クエリパラメータ」に修正しました。

2023-05-26 01:59 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +        });
修正漏れです。修正しました。

2023-05-26 01:59 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                // Cookieをリクエストスコープに移送
https://github.com/nablarch/nablarch-testing/pull/56#discussion_r1206151250
と同様のため、削除しました。

2023-05-26 02:39 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                    }
actualをデコードし、テストケースおよび失敗時の表示がいずれもデコード済みの値となるようにしました。

2023-05-26 06:09 UTC, kumagoro1202 requested changes

2023-05-26 06:09 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    }
```
createHttpRequestWithConversion(String requestUri,
            Map<String, String> commaSeparated, Map<String, String> cookie)
```
でも追加したメソッドを使うようにしましょう。

2023-05-26 06:09 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    private String percentEncodedString(String rawString) {
メソッド名が名詞なのは違和感があります。percentEncodeじゃないでしょうか。
百歩譲ってgetPercentEncodedStringならまだわかります。

2023-05-26 06:09 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +     * @return
`@param url`も中途半端な状態です。これだけだと「urlというパラメータ」にしかならないです。
descriptionを書いて「urlというパラメータは〇〇」という情報にしてください。

2023-05-26 06:09 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                            assertEquals(entry.getValue(), decodedResult);
tryの中でassertまですれば無駄にtryのスコープ外でdecodedResultを宣言する必要がないのでは。
```
                            try {
                                assertEquals(entry.getValue(), URLDecoder.decode(queryParamsMap.get(encodedKey), "UTF-8"));
                            } catch (UnsupportedEncodingException e) {
                                // ここには来ない
                                throw new RuntimeException(e);
                            }
```

2023-05-26 08:41 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    }
修正しました。

2023-05-26 08:57 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    private String percentEncodedString(String rawString) {
「percent encode」の語感に違和感があったので、「getPercentEncodedString」に修正しました。

2023-05-26 09:00 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +     * @return
修正しました。
また、呼び出し元が「requestUri」を引数に入れていることを考慮し、仮引数名を「uri」に変更しました。

2023-05-26 09:07 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                            assertEquals(entry.getValue(), decodedResult);
修正しました。

2023-05-26 10:44 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                            assertEquals(entry.getValue(), decodedResult);
try-catchをいっぱい書くの無駄だなーと思いました。あとここには来ないはずだったらRuntimeExceptionをリスローするより明示的にテストをfailさせるべきだと思います。↓こんな感じかと。
```
    /**
     * リクエストURIからクエリパラメータを取得する。
     * テスト用であるため、URIの厳密な解析は実施していない。
     * @param uri リクエストURI
     * @return クエリパラメータのマップ
     */
    private Map<String, String> getQueryParams(String uri) {
        String[] split = uri.split("\\?");
        if (split.length == 1) {
            return null;
        }

        String[] params = split[1].split("&");
        Map<String, String> result = new HashMap<String, String>();
        for (String param : params) {
            try {
                String decoded = URLDecoder.decode(param, "UTF-8");
                String[] keyValue = decoded.split("=");
                if (keyValue.length == 2) {
                    result.put(keyValue[0], keyValue[1]);
                } else {
                    result.put(keyValue[0], "");
                }
            } catch (UnsupportedEncodingException e) {
                fail("UTF8指定しているのでUnsupportedEncodingExceptionはthrowされない。(" +
                        e.getMessage() + ")");
            }
        }
        return result;
    }

    /**
     * クエリパラメータの設定が正しくなされていることを検証する。
     */
    @Test
    public void testQueryParamsNormal() {

        // テスト用にサブクラス化
        target = createMock(new HttpRequestHandler() {
            /** リクエストパラメータを変更し、200 OKを返却する。 */
            @Override
            public HttpResponse handle(HttpRequest req, ExecutionContext ctx) {
                // ボディを設定する。
                String body = Hereis.string();
                /*
                <html>
                  <head><title>test</title></head>
                  <body><p>Hello, World!</p></body>
                </html>
                */
                return new HttpResponse().write(body);
            }
        });

        // 実行
        target.execute("testQueryParamsNormal", new BasicAdvice() {
            @Override
            public void afterExecute(TestCaseInfo testCaseInfo,
                                     ExecutionContext context) {
                String no = testCaseInfo.getTestCaseNo();
                HttpRequest request = testCaseInfo.getHttpRequest();
                Map<String, String> queryParamsMap = getQueryParams(request.getRequestUri());
                if (no.equals("3")) {
                    // 3ケース目は、クエリパラメータを設定していないので空のはず
                    assertNull(queryParamsMap);
                } else {
                    // それ以外は、Excelに設定したクエリパラメータが設定されているはず
                    assert queryParamsMap != null;
                    Map<String, String> map = target.getListMap(
                            testCaseInfo.getSheetName(), "expectedQueryParams" + no).get(0);

                    for (Map.Entry<String, String> entry : map.entrySet()) {
                        if (entry.getValue() == null) {
                            assertNull(queryParamsMap.get(entry.getKey()));
                        } else {
                            assertEquals(entry.getValue(), queryParamsMap.get(entry.getKey()));
                        }
                    }
                }
            }
        });
    }
```

2023-05-26 10:54 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    private String percentEncodedString(String rawString) {
getPercentEncodedStringはやっぱり気持ち悪いです。「百歩譲って～まだわかる」は普通はやらないけどそうなってたら考え方の方向性は理解できなくはないくらいのニュアンスなので基本的にそれで例示されたもの使うのはやめた方がいいと思いますよ。。。
引数を変換してるのでgetという名前は違和感あります。「percent encode」の語感に違和感があるというのが私にはわかりませんが、それならいっそencodeとかでいいと思います。privateメソッドですし。

2023-05-26 11:31 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    private String percentEncodedString(String rawString) {
動詞の後に"String"が付くのが違和感がありましたが、"encode"だけのシンプルな記載でよいように感じました。
メソッド名を修正し、Javadocを付けました。

2023-05-26 11:32 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +                            assertEquals(entry.getValue(), decodedResult);
修正しました。

2023-05-26 11:43 UTC, chupaaaaaaan commented
masterブランチへのマージとなっていたため、クローズします。

2023-05-30 07:32 UTC, kumagoro1202 requested changes

2023-05-30 07:32 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +        // 後方互換性を考慮して、明示的に場合分けを行う。
example-webでオーバーライドしてるからではなく、公開APIとして定義されていたものなのでオーバーライドしている可能性があるから場合分けを行うとコメント修正してください。

2023-05-30 07:32 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +            List<Map<String, String>> expectedResponses,
口頭で伝えた通り、queryParamsが引数にない方のメソッドはTestCaseInfoをnewせずに、オーバーロードされたqueryParamsが引数にあるメソッドを呼び出すようにしてください。

2023-05-30 07:32 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/TestCaseInfo.java
> +        this(sheetName, testCaseParams, context, request, expectedResponseListMap, null, null);
ここにnullの追加は不要です。

2023-05-30 07:56 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +            List<Map<String, String>> expectedResponses,
修正しました。

2023-05-30 07:56 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/TestCaseInfo.java
> +        this(sheetName, testCaseParams, context, request, expectedResponseListMap, null, null);
修正しました。

2023-05-30 07:57 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +        // 後方互換性を考慮して、明示的に場合分けを行う。
修正しました。

2023-05-31 02:17 UTC, kumagoro1202 requested changes

2023-05-31 02:17 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +    @SuppressWarnings("unchecked")
キャストしてないのでsuppressする必要ないです。

2023-05-31 02:40 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +    @SuppressWarnings("unchecked")
アノテーションを削除しました。

2023-05-31 02:43 UTC, kumagoro1202 approved these changes

2023-05-31 02:43 UTC, merged