C1カバレッジの確認・警告の除去を実施しました
nablarch/nablarch-testing pull request #58
Opened 2023-06-07 05:25 UTC by chupaaaaaaan

2023-06-07 07:11 UTC, kumagoro1202 requested changes

2023-06-07 07:11 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/TestCaseInfoTest.java
> +        testCaseParams.put("expectedStatusCode", "200");
引数のMapを作るところはメソッド化して2つのテストで共有した方がいいと思います。
こんなイメージ。
```
    @Test
    public void クエリパラメータを指定しないコンストラクタで適切にインスタンスを生成できること() {

        TestCaseInfo sut = new TestCaseInfo("testSheet",
                createTestCaseParams(),
                createContext(),
                createRequestParams(),
                createExpectedResponseListMap(),
                createCookie());

        assertRequiredParams(sut);
        assertEquals("testCookieValue1", sut.getCookie().get("testCookieName1"));
        assertNull(sut.getQueryParams());
    }
```

2023-06-09 02:40 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/TestCaseInfoTest.java
> +        testCaseParams.put("expectedStatusCode", "200");
修正しました。

2023-06-09 04:01 UTC, kumagoro1202 requested changes

2023-06-09 04:01 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +        if (null != queryParams && !queryParams.isEmpty()) {
1055行目は直してないのなぜですか？

2023-06-09 04:01 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/TestCaseInfo.java
> +        if (null == queryParams || queryParams.isEmpty()) {
315行目は直してないのなぜですか？

2023-06-09 04:01 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/TestCaseInfoTest.java
> +        assertEquals("foobar", sut.getExpectedRequestScopeVar().get("requestScopedVar"));
今のままでもいいですが、先の指摘でこうしたらと例示したコード例では、必須の引数のアサートはこのテストの本質ではないのでまとめてもう一つのテストと共通化しているイメージでした。そうした方がクッキーとクエリパラメータにフォーカスされて見やすいと思いました。

2023-06-09 06:17 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/TestCaseInfo.java
> +        if (null == queryParams || queryParams.isEmpty()) {
`getCookie()`については、今回の修正で変更していないため、sonarqube指摘の対応方針を鑑み修正しない方が良い、と考えました。

2023-06-09 06:23 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +        if (null != queryParams && !queryParams.isEmpty()) {
```
createHttpRequestWithConversion(String requestUri, String httpMethod, Map<String, String> commaSeparated, Map<String, String> cookie)
```
にもともとあったロジックのため、sonarqube指摘の対応方針と合わせて修正しない方が良いとして修正していませんでしたが、今回の対応で、新しく追加した
```
createHttpRequestWithConversion(String requestUri, String httpMethod, Map<String, String> commaSeparated, Map<String, String> cookie, Map<String, String> queryParams)
```
の方にロジックが移っているため、修正するのが適切と考えました。

上記修正しました。

2023-06-09 06:33 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/TestCaseInfoTest.java
> +        assertEquals("foobar", sut.getExpectedRequestScopeVar().get("requestScopedVar"));
確かにそちらの方が見やすいので、共通のパラメータのテストは一つにまとめました。

2023-06-09 07:11 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/TestCaseInfo.java
> +        if (null == queryParams || queryParams.isEmpty()) {
このレベルの修正はほぼリスクないので範囲外でも対応してほしいです。書き方統一してない方が修正しないことよりデメリットがあると思います。

2023-06-09 07:27 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/TestCaseInfo.java
> +        if (null == queryParams || queryParams.isEmpty()) {
対応しました。

合わせて、他についても、警告が出ている部分は比較対象の入れ替えを実施しました。

2023-06-11 23:59 UTC, kumagoro1202 approved these changes

2023-06-12 00:00 UTC, merged