NTF/HTTPテストでHTTPメソッド指定可能にする対応で、インスペクションの警告を修正
nablarch/nablarch-testing pull request #65
Opened 2023-09-11 09:26 UTC by chupaaaaaaan

2023-09-12 04:53 UTC, kumagoro1202 requested changes

2023-09-12 04:53 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +    protected void clearPreviousTestData(@SuppressWarnings("unused") INF testCaseInfo) {
メソッド単位でSuppressしてください。

2023-09-12 04:53 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    private void initialize(HttpTestConfiguration config, @SuppressWarnings("unused") File dumpDir, String className) {
メソッド単位でSuppressしてください。

2023-09-12 04:53 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +        //noinspection rawtypes
メソッド単位でSuppressしてください。

2023-09-12 04:53 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    @SuppressWarnings("unused")
privateメソッドが使われていないならsuppressじゃなく消してください。

2023-09-12 04:53 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +        //noinspection AssignmentToStaticFieldFromInstanceMethod
メソッド単位でSuppressしてください。

2023-09-12 04:53 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +        ListWrapper.wrap(handlerQueue).select(SessionConcurrentAccessHandler.class);
使ってないから変数代入をやめるんじゃなくこの行自体削除してください。このメソッド読んでも何も意味がないです。

2023-09-12 04:53 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +            //noinspection AssignmentToStaticFieldFromInstanceMethod
メソッド単位にしてください。

2023-09-12 04:53 UTC, kumagoro1202 commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +            //noinspection ResultOfMethodCallIgnored
メソッド単位にしてください。

2023-09-12 04:53 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +        //noinspection ResultOfMethodCallIgnored
メソッド単位にしてください。

2023-09-12 04:53 UTC, kumagoro1202 commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +        //noinspection ResultOfMethodCallIgnored
メソッド単位にしてください。

2023-09-12 06:48 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/AbstractHttpRequestTestTemplate.java
> +    protected void clearPreviousTestData(@SuppressWarnings("unused") INF testCaseInfo) {
修正しました。

14b8205cda2febfc8e7aa31d826922517774dabb

2023-09-12 06:51 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    private void initialize(HttpTestConfiguration config, @SuppressWarnings("unused") File dumpDir, String className) {
修正しました。

cf1a2bcdebda56ca95e78a225a3ba86363702555

2023-09-12 06:54 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +        //noinspection rawtypes
修正しました。

d5898b74016efff2b8c6b2449eec2c64bb9982d6

2023-09-12 07:04 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +    @SuppressWarnings("unused")
修正しました。

b3ac0e9776793f705f32a19c78a44c4231696ca1

2023-09-12 07:09 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +        //noinspection AssignmentToStaticFieldFromInstanceMethod
修正しました。

2023-09-12 07:11 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +        ListWrapper.wrap(handlerQueue).select(SessionConcurrentAccessHandler.class);
修正しました。

ccbf27c66f56433d3d5fa89be263144fe2f65275

2023-09-12 07:12 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +            //noinspection AssignmentToStaticFieldFromInstanceMethod
修正しました。

dd66e2542fac05e2b6c134a7f9efda5052781556

2023-09-12 07:13 UTC, chupaaaaaaan commented on src/main/java/nablarch/test/core/http/HttpRequestTestSupport.java
> +            //noinspection ResultOfMethodCallIgnored
修正しました。

2541b38646d2df89f9a0624076d72b2d3d294c83

2023-09-12 07:15 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +        //noinspection ResultOfMethodCallIgnored
修正しました。

bf93f2cc09a8051bb4fc28766efef8d69f02ce7b

2023-09-12 07:15 UTC, chupaaaaaaan commented on src/test/java/nablarch/test/core/http/AbstractHttpRequestTestTemplateTest.java
> +        //noinspection ResultOfMethodCallIgnored
修正しました。

dad4643b07dfeb409d9adc6491cd18efe883ebcb

2023-09-14 01:57 UTC, chupaaaaaaan commented
不要なimport文を削除しました。

8dfc549eec313fb70a6477eb884f0c6c89f59217

2023-09-14 04:07 UTC, kumagoro1202 approved these changes

2023-09-14 04:07 UTC, merged